// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDZdZq9W-BJoZCJ5nQq2jDMzEfD9-i3vvQ',
    appId: '1:1098142687172:web:ee761737e18ca6753a0e91',
    messagingSenderId: '1098142687172',
    projectId: 'faris-apps-2440e',
    authDomain: 'faris-apps-2440e.firebaseapp.com',
    databaseURL: 'https://faris-apps-2440e-default-rtdb.firebaseio.com',
    storageBucket: 'faris-apps-2440e.appspot.com',
    measurementId: 'G-L05LM4QXNF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDWBloqxpxvy7-c6QUuRT_jcbcg_Li5A-E',
    appId: '1:1098142687172:android:00434fb2424bdde93a0e91',
    messagingSenderId: '1098142687172',
    projectId: 'faris-apps-2440e',
    databaseURL: 'https://faris-apps-2440e-default-rtdb.firebaseio.com',
    storageBucket: 'faris-apps-2440e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn8zBF9wVaz_1HbO7wnTZJaOJf9UTFnD8',
    appId: '1:1098142687172:ios:1f5f8f7e41ae806c3a0e91',
    messagingSenderId: '1098142687172',
    projectId: 'faris-apps-2440e',
    databaseURL: 'https://faris-apps-2440e-default-rtdb.firebaseio.com',
    storageBucket: 'faris-apps-2440e.appspot.com',
    iosClientId: '1098142687172-gan9vgu5hlk0iucel59p66ni4k7uq2uk.apps.googleusercontent.com',
    iosBundleId: 'com.example.farisApp',
  );
}
